include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-alfis
PKG_VERSION:=1.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for Alfis DNS
LUCI_DEPENDS:=+alfis +luci-base

PKG_LICENSE:=AGPL-3.0
PKG_MAINTAINER:=HodlOnToYourButts

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature